version: '3'

services:
  init-mongo-volume:
    image: busybox
    volumes:
      - mongo-data:/data/db
    command: ["sh", "-c", "docker volume create mongo-data || true"]

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      MONGODB_URI: mongodb://mongo:27017/mydatabase
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local
